# Generated by Django 4.1.6 on 2023-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lib1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_adj', models.CharField(max_length=40)),
                ('lib_verb', models.CharField(max_length=40)),
                ('lib_adj2', models.CharField(max_length=40)),
                ('lib_Noun', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lib2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib2_Noun', models.CharField(max_length=40)),
                ('lib2_verb', models.CharField(max_length=40)),
                ('lib2_adj', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lib3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib3_adj', models.CharField(max_length=40)),
                ('lib3_adj2', models.CharField(max_length=40)),
                ('lib3_body', models.CharField(max_length=40)),
                ('lib3_adj3', models.CharField(max_length=40)),
            ],
        ),
    ]
